# Generated by Django 3.1.5 on 2021-01-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragrances', '0003_auto_20210113_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragrancesmodel',
            name='first_family',
            field=models.ManyToManyField(to='fragrances.FirstFamilyModel', verbose_name='first family'),
        ),
    ]
